#pragma once
#include <QTextBrowser>
#include <QTextEdit>
#include <qboxlayout.h>
#include <qhash.h>
#include <qicon.h>
#include <qlabel.h>
#include <qlistwidget.h>
#include <qnamespace.h>
#include <qpainter.h>
#include <qstringtokenizer.h>
#include <qwidget.h>
