#pragma once
#include "libtrie/trie.hpp"
#include "omni-database.hpp"
#include "services/emoji-service/emoji.hpp"
#include <string_view>

/**
 * Provides all emoji-related services. Also integrates with the local sqlite database to provide
 * 'frequently used' metrics and all that.
 * The list of emojis is statically generated by a build script and is stored inside `emoji.cpp`.
 */

struct EmojiDataHash {
  size_t operator()(const EmojiData *data) { return std::hash<std::string_view>()(data->emoji); }
};

struct EmojiWithMetadata {
  const EmojiData *data = nullptr;
  uint32_t visitCount = 0;
  std::optional<QDateTime> pinnedAt;
};

class EmojiService {
  Trie<const EmojiData *, EmojiDataHash> m_index;
  OmniDatabase &m_db;

  void createDbEntry(std::string_view emoji);

public:
  /**
   * Synchronously build search index.
   */
  void buildIndex();
  std::vector<const EmojiData *> search(std::string_view query) const;

  std::vector<EmojiWithMetadata> getVisited() const;
  bool pin(std::string_view emoji);
  bool unpin(std::string_view emoji);
  bool registerVisit(std::string_view emoji);

  EmojiService(OmniDatabase &db);
};
