#pragma once
#include "libtrie/trie.hpp"
#include "services/emoji-service/emoji.hpp"
#include <string_view>

/**
 * Provides all emoji-related services. Also integrates with the local sqlite database to provide
 * 'frequently used' metrics and all that.
 * The list of emojis is statically generated by a build script and is stored inside `emoji.cpp`.
 */

struct EmojiDataHash {
  size_t operator()(const EmojiData *data) { return std::hash<std::string_view>()(data->emoji); }
};

class EmojiService {
  Trie<const EmojiData *, EmojiDataHash> m_index;

public:
  /**
   * Synchronously build search index.
   */
  void buildIndex();
  std::vector<const EmojiData *> search(std::string_view query) const;

  EmojiService();
};
